/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author henge
 */
public class GestionClientes extends javax.swing.JFrame {

    /**
     * Creates new form GestionClientes
     */
    public GestionClientes() {
        initComponents();
        setLocationRelativeTo(null);  // Esta línea centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonVertodoslosClientes = new javax.swing.JRadioButton();
        jRadioButtonAgregarClientes = new javax.swing.JRadioButton();
        jRadioButtonEliminarClientes = new javax.swing.JRadioButton();
        jRadioButtonEditarClientes = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Volver.setBackground(new java.awt.Color(153, 255, 255));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        Volver.setBorder(null);
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, 40));

        jRadioButtonVertodoslosClientes.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButtonVertodoslosClientes.setText("Ver todos los clientes");
        jRadioButtonVertodoslosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVertodoslosClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonVertodoslosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        jRadioButtonAgregarClientes.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButtonAgregarClientes.setText("Agregar clientes");
        jRadioButtonAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAgregarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonAgregarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jRadioButtonEliminarClientes.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButtonEliminarClientes.setText("Eliminar clientes");
        jRadioButtonEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEliminarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jRadioButtonEditarClientes.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButtonEditarClientes.setText("Editar Clientes");
        jRadioButtonEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEditarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonEditarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAgregarClientesActionPerformed
        // TODO add your handling code here:

        // si se selecciona el radio button de agregar clientes
        if (jRadioButtonAgregarClientes.isSelected()) {
            // se crea un objeto de la clase AgregarClientes
            RegistroUsuario agregarClientes = new RegistroUsuario();
            // se hace visible la ventana de AgregarClientes
            agregarClientes.setVisible(true);
            // se cierra la ventana actual
            this.dispose();
        }

    }//GEN-LAST:event_jRadioButtonAgregarClientesActionPerformed

    private void jRadioButtonEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEliminarClientesActionPerformed
        // TODO add your handling code here:

        // si se selecciona el radio button de eliminar clientes
        if (jRadioButtonEliminarClientes.isSelected()) {
            // se crea un objeto de la clase EliminarClientes
            
        }

    }//GEN-LAST:event_jRadioButtonEliminarClientesActionPerformed

    private void jRadioButtonEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEditarClientesActionPerformed
        // TODO add your handling code here:

        // si se selecciona el radio button de editar clientes
        if (jRadioButtonEditarClientes.isSelected()) {
            // se crea un objeto de la clase EditarClientes
          
        }
    }//GEN-LAST:event_jRadioButtonEditarClientesActionPerformed

    private void jRadioButtonVertodoslosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVertodoslosClientesActionPerformed
        // TODO add your handling code here:

        // si se selecciona el radio button de ver todos los clientes
        if (jRadioButtonVertodoslosClientes.isSelected()) {
            // se crea un objeto de la clase VerClientes
            
        }
    }//GEN-LAST:event_jRadioButtonVertodoslosClientesActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        //Validar si esta ventana fue abierta por un administrador o un gerente
        // si fue abierta por un administrador  se abre la ventana GestionUsuariosA y se cierra la ventana actual y si fue abierta por un gerente se abre la ventana GestionUsuariosG y se cierra la ventana actual
        // 3 es  el id del tipo de usuario gerente y 4 es el id del tipo de usuario administrador es tipo int

        if (Modelo.Logins.tipoUsuario == 3) {
            // se crea un objeto de la clase GestionUsuariosG
            GestionarUsuariosG gestionUsuariosG = new GestionarUsuariosG();
            // se hace visible la ventana de GestionUsuariosG
            gestionUsuariosG.setVisible(true);
            // se cierra la ventana actual
            this.dispose();
        } else if (Modelo.Logins.tipoUsuario == 4) {
            // se crea un objeto de la clase GestionUsuariosA
            GestionarUsuariosA gestionUsuariosA = new GestionarUsuariosA();
            // se hace visible la ventana de GestionUsuariosA
            gestionUsuariosA.setVisible(true);
            // se cierra la ventana actual
            this.dispose();
        }







    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAgregarClientes;
    private javax.swing.JRadioButton jRadioButtonEditarClientes;
    private javax.swing.JRadioButton jRadioButtonEliminarClientes;
    private javax.swing.JRadioButton jRadioButtonVertodoslosClientes;
    // End of variables declaration//GEN-END:variables
}
