package Vista;

/**
 *
 * @author henge
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLABEL = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        InputContra = new javax.swing.JTextField();
        InputUsuario = new javax.swing.JTextField();
        IngresarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        RadioCliente1 = new javax.swing.JRadioButton();
        RadioCliente2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloLABEL.setBackground(new java.awt.Color(102, 255, 255));
        TituloLABEL.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        TituloLABEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLABEL.setText("Login");
        jPanel1.add(TituloLABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));

        UsuarioLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UsuarioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuarioLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jPanel1.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 20));

        ContraseñaLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ContraseñaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContraseñaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-con-llave.png"))); // NOI18N
        jPanel1.add(ContraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 90, 20));

        InputContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(InputContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        InputUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(InputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 160, -1));

        IngresarButton.setBackground(new java.awt.Color(153, 255, 255));
        IngresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar.png"))); // NOI18N
        IngresarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IngresarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(IngresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 90, -1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButton2.setText("jButton1");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        RadioCliente1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        RadioCliente1.setText("Cliente");
        RadioCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(RadioCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, -1));

        RadioCliente2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        RadioCliente2.setText("Veterinario");
        RadioCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RadioCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCliente2ActionPerformed(evt);
            }
        });
        jPanel1.add(RadioCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarButtonActionPerformed

    private void RadioCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCliente1ActionPerformed

    private void RadioCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCliente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JButton IngresarButton;
    private javax.swing.JTextField InputContra;
    private javax.swing.JTextField InputUsuario;
    private javax.swing.JRadioButton RadioCliente1;
    private javax.swing.JRadioButton RadioCliente2;
    private javax.swing.JLabel TituloLABEL;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
