/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author henge
 */
public class VentaProducto extends javax.swing.JFrame {

    /**
     * Creates new form VentaProducto
     */
    public VentaProducto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        JPANELSCOLLProductos = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        LabelImagen1 = new javax.swing.JLabel();
        LabelTitulo1 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        LabelImagen2 = new javax.swing.JLabel();
        Labeltitulo2 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        LabelImagen3 = new javax.swing.JLabel();
        Labeltitulo3 = new javax.swing.JLabel();
        Panel4 = new javax.swing.JPanel();
        LabelImagen4 = new javax.swing.JLabel();
        Labeltitulo4 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        LabelImagen5 = new javax.swing.JLabel();
        Labeltitulo5 = new javax.swing.JLabel();
        Panel6 = new javax.swing.JPanel();
        LabelImagen6 = new javax.swing.JLabel();
        Labeltitulo6 = new javax.swing.JLabel();
        Panel7 = new javax.swing.JPanel();
        LabelImagen7 = new javax.swing.JLabel();
        Labeltitulo7 = new javax.swing.JLabel();
        Panel8 = new javax.swing.JPanel();
        LabelImagen8 = new javax.swing.JLabel();
        Labeltitulo8 = new javax.swing.JLabel();
        Panel9 = new javax.swing.JPanel();
        LabelImagen9 = new javax.swing.JLabel();
        Labeltitulo9 = new javax.swing.JLabel();
        Panel10 = new javax.swing.JPanel();
        LabelImagen10 = new javax.swing.JLabel();
        Labeltitulo10 = new javax.swing.JLabel();
        Panel11 = new javax.swing.JPanel();
        LabelImagen11 = new javax.swing.JLabel();
        Labeltitulo11 = new javax.swing.JLabel();
        Panel12 = new javax.swing.JPanel();
        LabelImagen12 = new javax.swing.JLabel();
        Labeltitulo12 = new javax.swing.JLabel();
        Panelinformacion = new javax.swing.JPanel();
        InformaciónProducto = new javax.swing.JTextArea();
        BTNVerCarrito = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BTNAgregarCarrito = new javax.swing.JButton();
        InputCantidad = new javax.swing.JTextField();
        TituloCantidad = new javax.swing.JLabel();
        LabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        PanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPANELSCOLLProductos.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(0, 204, 204));
        Panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OIG3.jpeg"))); // NOI18N
        Panel1.add(LabelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        LabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTitulo1.setText("Shampoo perro");
        Panel1.add(LabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, -1, -1));

        jPanel2.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 160));

        Panel2.setBackground(new java.awt.Color(0, 204, 204));
        Panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fabricante-de-medicamentos-veterinarios-advacare-pharma.png"))); // NOI18N
        Panel2.add(LabelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 80));

        Labeltitulo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo2.setText("Antiparasitarios");
        Panel2.add(Labeltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, -1, -1));

        jPanel2.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 160));

        Panel3.setBackground(new java.awt.Color(0, 204, 204));
        Panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpeg"))); // NOI18N
        Panel3.add(LabelImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo3.setText("Cepillos");
        Panel3.add(Labeltitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, -1));

        jPanel2.add(Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 160, 160));

        Panel4.setBackground(new java.awt.Color(0, 204, 204));
        Panel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YThhZGU3OG-1000x1000.jpg"))); // NOI18N
        Panel4.add(LabelImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo4.setText("Camas");
        Panel4.add(Labeltitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 90, -1));

        jPanel2.add(Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 160));

        Panel5.setBackground(new java.awt.Color(0, 204, 204));
        Panel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/L_lallala7553.jpg"))); // NOI18N
        Panel5.add(LabelImagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo5.setText("jaulas para viajar");
        Panel5.add(Labeltitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, -1, -1));

        jPanel2.add(Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 160));

        Panel6.setBackground(new java.awt.Color(0, 204, 204));
        Panel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/a49f8897be14451e1f22cbb0749f29cc.jpg"))); // NOI18N
        Panel6.add(LabelImagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo6.setText("Juguetes");
        Panel6.add(Labeltitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, -1));

        jPanel2.add(Panel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 160, 160));

        Panel7.setBackground(new java.awt.Color(0, 204, 204));
        Panel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Todas-las-marcas-de-pienso-para-perro-365x240.jpg"))); // NOI18N
        Panel7.add(LabelImagen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo7.setText("Alimentos");
        Panel7.add(Labeltitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 90, -1));

        jPanel2.add(Panel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 160));

        Panel8.setBackground(new java.awt.Color(0, 204, 204));
        Panel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/set-de-cepillos-para-perros-3-piezas_2_g.jpeg"))); // NOI18N
        Panel8.add(LabelImagen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo8.setText("Peines");
        Panel8.add(Labeltitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 90, -1));

        jPanel2.add(Panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 160, 160));

        Panel9.setBackground(new java.awt.Color(0, 204, 204));
        Panel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelImagen9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen9.setText("Ropa");
        Panel9.add(LabelImagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 90, -1));

        Labeltitulo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/s-l640.jpg"))); // NOI18N
        Panel9.add(Labeltitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        jPanel2.add(Panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 160, 160));

        Panel10.setBackground(new java.awt.Color(0, 204, 204));
        Panel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CHAMPU-DE-PAPAYA-MIEL-EASYGROOM-PARA-GATOS.png"))); // NOI18N
        Panel10.add(LabelImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo10.setText("Shampoo gato");
        Panel10.add(Labeltitulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, -1, -1));

        jPanel2.add(Panel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, 160));

        Panel11.setBackground(new java.awt.Color(0, 204, 204));
        Panel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Credelio.png"))); // NOI18N
        Panel11.add(LabelImagen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo11.setText("Antipulgas");
        Panel11.add(Labeltitulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 122, 90, -1));

        jPanel2.add(Panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 160, 160));

        Panel12.setBackground(new java.awt.Color(0, 204, 204));
        Panel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelImagen12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelImagen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (1).jpeg"))); // NOI18N
        Panel12.add(LabelImagen12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 7, 158, 103));

        Labeltitulo12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Labeltitulo12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labeltitulo12.setText("Comederos y bebederos");
        Panel12.add(Labeltitulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        jPanel2.add(Panel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 160, 160));

        JPANELSCOLLProductos.setViewportView(jPanel2);

        PanelPrincipal.add(JPANELSCOLLProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 690));

        Panelinformacion.setBackground(new java.awt.Color(153, 255, 255));
        Panelinformacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panelinformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InformaciónProducto.setEditable(false);
        InformaciónProducto.setBackground(new java.awt.Color(255, 255, 255));
        InformaciónProducto.setColumns(20);
        InformaciónProducto.setRows(5);
        InformaciónProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panelinformacion.add(InformaciónProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 230));

        BTNVerCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        BTNVerCarrito.setText("Ver carrito");
        BTNVerCarrito.setToolTipText("");
        BTNVerCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNVerCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNVerCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVerCarritoActionPerformed(evt);
            }
        });
        Panelinformacion.add(BTNVerCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 40));

        BtnVolver.setBackground(new java.awt.Color(153, 255, 255));
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        BtnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        Panelinformacion.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 70, 30));

        BTNAgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        BTNAgregarCarrito.setText("Agregar al carrito");
        BTNAgregarCarrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTNAgregarCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregarCarritoActionPerformed(evt);
            }
        });
        Panelinformacion.add(BTNAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 40));

        InputCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Panelinformacion.add(InputCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 90, -1));

        TituloCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCantidad.setText("Cantidad ");
        Panelinformacion.add(TituloCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 60, -1));

        LabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo (1).png"))); // NOI18N
        Panelinformacion.add(LabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        PanelPrincipal.add(Panelinformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 590, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregarCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNAgregarCarritoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BTNVerCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVerCarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVerCarritoActionPerformed

    //Hacer una funcion que cuando se pase el cursos sobre los paneles adentro del PanelScroll se sobre salga el panel dandole un efecto 
    //de que se esta seleccionando
    //Hacer una funcion que cuando se de click en un panel se muestre la informacion del producto en el PanelInformacion

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregarCarrito;
    private javax.swing.JButton BTNVerCarrito;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextArea InformaciónProducto;
    private javax.swing.JTextField InputCantidad;
    private javax.swing.JScrollPane JPANELSCOLLProductos;
    private javax.swing.JLabel LabelImagen1;
    private javax.swing.JLabel LabelImagen10;
    private javax.swing.JLabel LabelImagen11;
    private javax.swing.JLabel LabelImagen12;
    private javax.swing.JLabel LabelImagen2;
    private javax.swing.JLabel LabelImagen3;
    private javax.swing.JLabel LabelImagen4;
    private javax.swing.JLabel LabelImagen5;
    private javax.swing.JLabel LabelImagen6;
    private javax.swing.JLabel LabelImagen7;
    private javax.swing.JLabel LabelImagen8;
    private javax.swing.JLabel LabelImagen9;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JLabel Labeltitulo10;
    private javax.swing.JLabel Labeltitulo11;
    private javax.swing.JLabel Labeltitulo12;
    private javax.swing.JLabel Labeltitulo2;
    private javax.swing.JLabel Labeltitulo3;
    private javax.swing.JLabel Labeltitulo4;
    private javax.swing.JLabel Labeltitulo5;
    private javax.swing.JLabel Labeltitulo6;
    private javax.swing.JLabel Labeltitulo7;
    private javax.swing.JLabel Labeltitulo8;
    private javax.swing.JLabel Labeltitulo9;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel10;
    private javax.swing.JPanel Panel11;
    private javax.swing.JPanel Panel12;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel Panel7;
    private javax.swing.JPanel Panel8;
    private javax.swing.JPanel Panel9;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Panelinformacion;
    private javax.swing.JLabel TituloCantidad;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
